AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: from_sns.handler
      Runtime: python3.9
      Architectures:
        - arm64