AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ImageCipher:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        # - arm64
        - x86_64
      Timeout: 10
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
