name: check-py-requirements

outputs:
  is-update-required:
    value: ${{ steps.check-requirements.outputs.run-job }}

runs:
  using: "composite"
  steps:
    - name: Check requirements.txt
      id: check-requirements
      shell: bash
      run: |
        echo "=============== list modified files ==============="
        git diff --name-only HEAD^ HEAD

        echo "========== check paths of modified files =========="
        found=false

        git diff --name-only HEAD^ HEAD > files.txt
        while IFS= read -r file
        do
          if [[ $file = "requirements.txt" ]]; then
            echo "requirements.txt was updated, update lambda layers required"
            echo "run-job=true" >> $GITHUB_OUTPUT
            found=true
            break
          fi
        done < files.txt

        if [ "$found" = false ]; then
            echo "No lambda layers update needed"
            echo "run-job=false" >> $GITHUB_OUTPUT
        fi
