name: build-lambda-layers

inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true
  require_update_layer:
    required: true

runs:
  using: "composite"
  steps:
    # For more info: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Zip source code
      shell: bash
      run: |
        zip -r code.zip entrypoint internal

    - name: Zip definitions
      shell: bash
      run: |
        {
          echo '{'
          echo '  "sha": "${{ github.sha }}",'
          echo '  "branch": "${{ env.branch_name }}",'
          echo '  "id": "${{ env.short_id }}",'
          echo '  "repo": "${{ env.repo }}",'
          echo '  "service_name": "${{ env.service_name }}",'
          echo '  "require_update_layer": ${{ inputs.require_update_layer }}'
          echo '}'
        } > definitions.json
        #echo '{"sha": "${{ github.sha }}", "branch": "${{ github.head_ref }}", "id": "${{ env.short_id }}", "repo": "${{ env.repo }}" }' > definitions.json
        cat definitions.json
        zip -r info.zip definitions.json

    - name: Upload source code to artifact manager
      shell: bash
      run: |
        path_key="$release_bucket_uri/$service_name/$branch_name/"
        cd_path_key="$release_bucket_uri/$service_name/continuous-deployment-dev/"
        echo "$path_key"
        aws s3 cp code.zip $path_key
        aws s3 cp info.zip $cd_path_key
